/**:
  traversability_node:
    ros__parameters:
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      pointcloud_topic_name: "/hesai/points"
      use_lidar_pointcloud: true
      publish_traversability_grid: true
      is_kf_optimization_enabled: true
      slam_frame: base_link
      robot_base_frame: base_link
      lidar_frame: hesai_lidar

  local_traversability_node:
    ros__parameters:
      pointcloud_topic_name: "/hesai/points"
      expected_frequency: 10.0 # Hz.
      slam_frame: base_link
      robot_base_frame: base_link
      lidar_frame: hesai_lidar

  traversability_threshold_node:
    ros__parameters:
      lethal_obstacle_threshold: 55 # between 0 to 100

  slam_keyframe_pcl_simulator:
    ros__parameters:
      odom_topic: "/glim_ros/odom_corrected"
      pcl_topic: "/hesai/points"
      keyframe_publish_rate_hz: 5.0 # Hz.
