# networks:
#   ros2-net:
#   link-local-net:
#     driver: macvlan
#     driver_opts:
#       parent: enp86s0  # Specify your parent network interface (e.g., enp86s0)
#     ipam:
#       config:
#         - subnet: 169.254.0.0/16
#           gateway: 169.254.0.1

services:
  openzen:
    image: docker-openzen:latest
    build:
     context: .
     dockerfile: openzen/openzen.Dockerfile
    container_name: openzen
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/openzen-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/openzen/OpenZenNode.cpp:/root/ros2_ws/src/openzenros2/src/OpenZenNode.cpp
      - ../sensor_configs/openzen/openzen_lpms.launch.py:/root/ros2_ws/src/openzenros2/launch/openzen_lpms.launch.py
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/openzen-launch.sh

  rm3100:
    build:
      context: .
      dockerfile: rm3100/rm3100.Dockerfile
    container_name: rm3100
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/rm3100-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/rm3100/params.yaml:/root/ros2_ws/src/go1_magnetometer_rm3100/config/params.yaml:rw
      - ../sensor_configs/rm3100/rm3100_driver.launch.py:/root/ros2_ws/src/go1_magnetometer_rm3100/launch/rm3100_driver.launch.py:rw
      - ../sensor_configs/rm3100/rm3100_driver.py:/root/ros2_ws/src/go1_magnetometer_rm3100/src/rm3100_driver.py:rw
      - ../ros2_ws/src/imu_mag_fusion:/root/ros2_ws/src/imu_mag_fusion
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/rm3100-launch.sh

  emlid:
    build:
      context: .
      dockerfile: emlid/emlid.Dockerfile
    container_name: emlid
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/emlid-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/emlid/nmea_serial_driver.py:/root/ros2_ws/src/nmea_navsat_driver/src/libnmea_navsat_driver/nodes/nmea_serial_driver.py:rw
      - ../sensor_configs/emlid/nmea_serial_driver.yaml:/root/ros2_ws/src/nmea_navsat_driver/config/nmea_serial_driver.yaml:rw
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/emlid-launch.sh

  realsense:
    image: docker-realsense:latest
    build:
      context: .
      dockerfile: realsense/realsense.Dockerfile
    container_name: realsense
    privileged: true
    # profiles: ["realsense-raw"]
    network_mode: host
    environment:
      REALSENSE_COLOR_CAMERA_INFO_URL: ""
      REALSENSE_ALIGNED_DEPTH_TO_COLOR_CAMERA_INFO_URL: ""
      REALSENSE_COMPRESS_MODE: "none"
      REALSENSE_COMPRESS_TOPICS: "/camera/color/image_raw"
      COMPRESS_PNG_LEVEL: "1"
      COMPRESS_FFMPEG_ENCODER: "libx264rgb"
      COMPRESS_FFMPEG_ENCODER_AV_OPTIONS: "preset:ultrafast,crf:0"
      COMPRESS_FFMPEG_BIT_RATE: "20000000"
      COMPRESS_FFMPEG_GOP_SIZE: "10"
      COMPRESS_FFMPEG_QMAX: "1"
      ROS_DOMAIN_ID: 30
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/realsense-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/realsense/:/root/sensor_configs/realsense/:rw
      - ../sensor_configs/realsense/rs_launch.py:/root/ros2_ws/src/realsense-ros/realsense2_camera/launch/rs_launch.py:rw
      - ../ros2_ws/src/realsense_camera_info_override:/root/ros2_ws/src/realsense_camera_info_override:rw
    command: /root/shared_folder/realsense-launch.sh
  # realsense_png:
  #   image: docker-realsense:latest
  #   build:
  #     context: .
  #     dockerfile: realsense/realsense.Dockerfile
  #   container_name: realsense-png
  #   profiles: ["realsense-png"]
  #   privileged: true
  #   networks:
  #     - ros2-net
  #   environment:
  #     REALSENSE_COLOR_CAMERA_INFO_URL: ""
  #     REALSENSE_ALIGNED_DEPTH_TO_COLOR_CAMERA_INFO_URL: ""
  #     REALSENSE_COMPRESS_MODE: "compressed"
  #     REALSENSE_COMPRESS_TOPICS: "/camera/color/image_raw"
  #     COMPRESS_PNG_LEVEL: "1"
  #     COMPRESS_FFMPEG_ENCODER: "libx264rgb"
  #     COMPRESS_FFMPEG_ENCODER_AV_OPTIONS: "preset:ultrafast,crf:0"
  #     COMPRESS_FFMPEG_BIT_RATE: "20000000"
  #     COMPRESS_FFMPEG_GOP_SIZE: "10"
  #     COMPRESS_FFMPEG_QMAX: "1"
  #   volumes:
  #     - /dev/:/dev/
  #     - ../ros2_ws/build/realsense-build:/root/ros2_ws/build
  #     - ../shared_folder/:/root/shared_folder/
  #     - ../sensor_configs/realsense/:/root/sensor_configs/realsense/:rw
  #     - ../sensor_configs/realsense/rs_launch.py:/root/ros2_ws/src/realsense-ros/realsense2_camera/launch/rs_launch.py:rw
  #     - ../ros2_ws/src/realsense_camera_info_override:/root/ros2_ws/src/realsense_camera_info_override:rw
    # environment:
    #   #- ROS_DOMAIN_ID=42
  #   command: /root/shared_folder/realsense-launch.sh
  # realsense_ffmpeg:
  #   image: docker-realsense:latest
  #   build:
  #     context: .
  #     dockerfile: realsense/realsense.Dockerfile
  #   container_name: realsense-ffmpeg
  #   #profiles: ["realsense-ffmpeg"]
  #   privileged: true
  #   networks:
  #     - ros2-net
  #   environment:
  #     REALSENSE_COLOR_CAMERA_INFO_URL: ""
  #     REALSENSE_ALIGNED_DEPTH_TO_COLOR_CAMERA_INFO_URL: ""
  #     REALSENSE_COMPRESS_MODE: "ffmpeg"
  #     REALSENSE_COMPRESS_TOPICS: "/camera/color/image_raw"
  #     COMPRESS_PNG_LEVEL: "1"
  #     COMPRESS_FFMPEG_ENCODER: "libx264rgb"
  #     COMPRESS_FFMPEG_ENCODER_AV_OPTIONS: "preset:ultrafast,crf:0"
  #     COMPRESS_FFMPEG_BIT_RATE: "20000000"
  #     COMPRESS_FFMPEG_GOP_SIZE: "10"
  #     COMPRESS_FFMPEG_QMAX: "1"
  #   volumes:
  #     - /dev/:/dev/
  #     - ../ros2_ws/build/realsense-build:/root/ros2_ws/build
  #     - ../shared_folder/:/root/shared_folder/
  #     - ../sensor_configs/realsense/:/root/sensor_configs/realsense/:rw
  #     - ../sensor_configs/realsense/rs_launch.py:/root/ros2_ws/src/realsense-ros/realsense2_camera/launch/rs_launch.py:rw
  #     - ../ros2_ws/src/realsense_camera_info_override:/root/ros2_ws/src/realsense_camera_info_override:rw
    # environment:
    #   #- ROS_DOMAIN_ID=42
  #   command: /root/shared_folder/realsense-launch.sh

  ouster:
    image: docker-ouster:latest
    build:
      context: .
      dockerfile: ouster/os.Dockerfile
    container_name: ouster
    privileged: true
    network_mode: host
    # ports:
    #   - "7502:7502/udp"
    #   - "7503:7503/udp"
    volumes:
      - ../ros2_ws/build/ouster-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/ouster/driver_params.yaml:/root/ros2_ws/src/ouster-ros/ouster-ros/config/driver_params.yaml:rw
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/ouster-launch.sh

  # mapir:
  #   image: docker-mapir:latest
  #   build:
  #     context: .
  #     dockerfile: mapir/mapir.Dockerfile
  #   container_name: mapir
  #   privileged: true
  #   profiles: ["mapir-raw"]
  #   networks:
  #     - ros2-net
  #   environment:
  #     MAPIR_COMPRESS_MODE: "none"
  #     MAPIR_COMPRESS_TOPICS: "/mapir/image_raw"
  #     COMPRESS_PNG_LEVEL: "1"
  #     COMPRESS_FFMPEG_ENCODER: "libx264rgb"
  #     COMPRESS_FFMPEG_ENCODER_AV_OPTIONS: "preset:ultrafast,crf:0"
  #     COMPRESS_FFMPEG_BIT_RATE: "20000000"
  #     COMPRESS_FFMPEG_GOP_SIZE: "10"
  #     COMPRESS_FFMPEG_QMAX: "1"
  #   volumes:
  #     - /dev/:/dev/
  #     - ../ros2_ws/build/mapir-build:/root/ros2_ws/build
  #     - ../shared_folder/:/root/shared_folder/
  #     - ../sensor_configs/mapir/:/root/sensor_configs/mapir/:rw
  #     - ../sensor_configs/mapir/mapir_camera_params.yaml:/root/ros2_ws/src/mapir-camera-ros2/config/mapir_camera_params.yaml:rw
  #     - ../sensor_configs/mapir/mapir_camera.launch.py:/root/ros2_ws/src/mapir-camera-ros2/launch/mapir_camera.launch.py:rw
    # environment:
    #   #- ROS_DOMAIN_ID=42
  #   command: /root/shared_folder/mapir-launch.sh
  # mapir_png:
  #   image: docker-mapir:latest
  #   build:
  #     context: .
  #     dockerfile: mapir/mapir.Dockerfile
  #   container_name: mapir-png
  #   profiles: ["mapir-png"]
  #   privileged: true
  #   networks:
  #     - ros2-net
  #   environment:
  #     MAPIR_COMPRESS_MODE: "compressed"
  #     MAPIR_COMPRESS_TOPICS: "/mapir/image_raw"
  #     COMPRESS_PNG_LEVEL: "1"
  #     COMPRESS_FFMPEG_ENCODER: "libx264rgb"
  #     COMPRESS_FFMPEG_ENCODER_AV_OPTIONS: "preset:ultrafast,crf:0"
  #     COMPRESS_FFMPEG_BIT_RATE: "20000000"
  #     COMPRESS_FFMPEG_GOP_SIZE: "10"
  #     COMPRESS_FFMPEG_QMAX: "1"
  #   volumes:
  #     - /dev/:/dev/
  #     - ../ros2_ws/build/mapir-build:/root/ros2_ws/build
  #     - ../shared_folder/:/root/shared_folder/
  #     - ../sensor_configs/mapir/:/root/sensor_configs/mapir/:rw
  #     - ../sensor_configs/mapir/mapir_camera_params.yaml:/root/ros2_ws/src/mapir-camera-ros2/config/mapir_camera_params.yaml:rw
  #     - ../sensor_configs/mapir/mapir_camera.launch.py:/root/ros2_ws/src/mapir-camera-ros2/launch/mapir_camera.launch.py:rw
    # environment:
    #   #- ROS_DOMAIN_ID=42
  #   command: /root/shared_folder/mapir-launch.sh
  mapir_ffmpeg:
    image: docker-mapir:latest
    build:
      context: .
      dockerfile: mapir/mapir.Dockerfile
    container_name: mapir-ffmpeg
    #profiles: ["mapir-ffmpeg"]
    privileged: true
    network_mode: host
    environment:
      MAPIR_COMPRESS_MODE: "ffmpeg"
      MAPIR_COMPRESS_TOPICS: "/mapir/image_raw"
      COMPRESS_PNG_LEVEL: "1"
      COMPRESS_FFMPEG_ENCODER: "libx264rgb"
      COMPRESS_FFMPEG_ENCODER_AV_OPTIONS: "preset:ultrafast,crf:0"
      COMPRESS_FFMPEG_BIT_RATE: "20000000"
      COMPRESS_FFMPEG_GOP_SIZE: "10"
      COMPRESS_FFMPEG_QMAX: "1"
      ROS_DOMAIN_ID: 30
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/mapir-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/mapir/:/root/sensor_configs/mapir/:rw
      - ../sensor_configs/mapir/mapir_camera_params.yaml:/root/ros2_ws/src/mapir-camera-ros2/config/mapir_camera_params.yaml:rw
      - ../sensor_configs/mapir/mapir_camera.launch.py:/root/ros2_ws/src/mapir-camera-ros2/launch/mapir_camera.launch.py:rw
    command: /root/shared_folder/mapir-launch.sh

  curt:
    image: docker-curt:latest
    build:
      context: .
      dockerfile: curt/curt.Dockerfile
    container_name: curt
    privileged: true
    network_mode: host
    volumes:
      - ../ros2_ws/build/curt-build:/root/ros2_ws/build
      - ../ros2_ws/src/curt_description:/root/ros2_ws/src/curt_description
      - ../shared_folder/:/root/shared_folder/
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/curt-launch.sh

  recorder:
    image: docker-recorder:latest
    build:
      context: .
      dockerfile: recorder/recorder.Dockerfile
    container_name: recorder
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../../rosbags:/root/rosbags/
      - ../ros2_ws/build/recorder-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/recorder-launch.sh

  ## Extra Sensors

  evk4:
    image: docker-evk4:latest
    build:
      context: .
      dockerfile: evk4/evk4.Dockerfile
    container_name: evk4
    privileged: true
    network_mode: host
    volumes:
      - ../shared_folder/:/root/shared_folder/
    environment:
      - ROS_DOMAIN_ID=30
    command:  /root/shared_folder/evk4-launch.sh

  # ikalibr:
  #   image: ulong2/ie_kalibr_image:latest
  #   container_name: ikalibr
  #   privileged: true
  #   networks:
  #     - ros2-net
  #   volumes:
  #     - /dev/:/dev/
  #     - ../../rosbags:/root/rosbags/
  #     - ../shared_folder/:/root/shared_folder/
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   environment:
  #     - DISPLAY=$DISPLAY
      # #- ROS_DOMAIN_ID=42
  #   command: bin/bash

  # xsens:
  #   build:
  #     context: .
  #     dockerfile: xsens/xsens.Dockerfile
  #   container_name: xsens
  #   privileged: true
  #   networks:
  #     - ros2-net
  #   volumes:
  #     - /dev/:/dev/
  #     - ../ros2_ws/build/xsens-build:/root/ros2_ws/build
  #     - ../shared_folder/:/root/shared_folder/
  #     - ../sensor_configs/xsens/mtdevice.py:/root/ros2_ws/src/norlab_xsens_driver/xsens_driver/mtdevice.py:rw
  #     - ../sensor_configs/xsens/mtnode.py:/root/ros2_ws/src/norlab_xsens_driver/xsens_driver/mtnode.py:rw
  #     - ../sensor_configs/xsens/xsens_driver.launch.xml:/root/ros2_ws/src/norlab_xsens_driver/launch/xsens_driver.launch.xml:rw
    # environment:
    #   #- ROS_DOMAIN_ID=42
  #   command: /root/shared_folder/xsens-launch.sh

  foxglove:
    build:
      context: .
      dockerfile: foxglove/foxglove.Dockerfile
    container_name: foxglove
    privileged: true
    # ports:
    #   - "9092:9092"
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../../rosbags/:/root/rosbags/
      - ../ros2_ws/build/foxglove-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../ros2_ws/src/curt_description:/root/ros2_ws/src/curt_description
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/foxglove-launch.sh
    
### NAVIGATION PIPELINE ###

  traversability_ros2:
    build:
     context: .
     dockerfile: traversability_mapping/traversability_mapping_ros2.Dockerfile
    container_name: trav_ros2
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/trav_ros2-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../ros2_ws/src/traversability_mapping_ros2:/root/ros2_ws/src/traversability_mapping_ros2
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/trav_ros2-launch.sh

  hmr_localisation:
    build:
     context: .
     dockerfile: hmr_localisation/hmr.Dockerfile
    container_name: hmr_localisation
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../ros2_ws/build/hmr-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/hmr_localisation/gt_ouster_ndt.yaml:/root/ros2_ws/src/hmr_localisation/config/gt_ouster_ndt.yaml:rw
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/hmr-launch.sh

  glim:
    build:
     context: .
     dockerfile: glim/glim.Dockerfile
    container_name: glim
    privileged: true
    network_mode: host
    volumes:
      - /dev/:/dev/
      - ../../rosbags/:/root/rosbags/
      - ../ros2_ws/build/glim-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../ros2_ws/src/glim:/root/ros2_ws/src/glim
      - ../ros2_ws/src/glim_ros2:/root/ros2_ws/src/glim_ros2
      - ../ros2_ws/src/glim_ext:/root/ros2_ws/src/glim_ext
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/glim-launch.sh

  nav2:
    build:
      context: .
      dockerfile: nav2/nav2.Dockerfile
    container_name: nav2
    network_mode: host
    volumes:
      - ../ros2_ws/build/nav2-build:/root/ros2_ws/build
      - ../shared_folder/:/root/shared_folder/
      - ../sensor_configs/nav2:/root/nav2
      - ../sensor_configs/nav2/navigation_launch.py:/opt/ros/kilted/share/nav2_bringup/launch/navigation_launch.py:rw
      - ../sensor_configs/nav2/bringup_launch.py:/opt/ros/kilted/share/nav2_bringup/launch/bringup_launch.py:rw
    environment:
      - ROS_DOMAIN_ID=30
    command: /root/shared_folder/nav2-launch.sh