/**:
  traversability_node:
    ros__parameters:
      additions_topic_name: "traversability_keyframe_additions"
      updates_topic_name: "traversability_keyframe_updates"
      pointcloud_topic_name: "/glim_ros/points_corrected"
      use_lidar_pointcloud: true
      publish_traversability_grid: true
      is_kf_optimization_enabled: true
      slam_frame: base_link
      robot_base_frame: base_link
      lidar_frame: imu_link

  local_traversability_node:
    ros__parameters:
      pointcloud_topic_name: "/glim_ros/points_corrected"
      expected_frequency: 4.0 # Hz.
      slam_frame: base_link
      robot_base_frame: base_link
      lidar_frame: imu_link

  traversability_threshold_node:
    ros__parameters:
      lethal_obstacle_threshold: 80 # between 0 to 100

  slam_keyframe_pcl_simulator:
    ros__parameters:
      odom_topic: "/glim_ros/odom_corrected"
      pcl_topic: "/glim_ros/points_corrected"
      keyframe_publish_rate_hz: 5.0 # Hz.
